# Generated by Django 5.1.5 on 2025-02-19 20:01

import django.db.models.deletion
import template_reports.models.utils
from django.db import migrations, models
import swapper

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        swapper.dependency('template_reports', 'ReportDefinition'),
        swapper.dependency('template_reports', 'ReportRun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(storage=template_reports.models.utils.get_storage, upload_to='template_reports/templates/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'swappable': swapper.swappable_setting('template_reports', 'ReportDefinition'),
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('file', models.FileField(storage=template_reports.models.utils.get_storage, upload_to='template_reports/generated_reports/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=swapper.get_model_name('template_reports', 'ReportDefinition'))),
            ],
            options={
                'swappable': swapper.swappable_setting('template_reports', 'ReportRun'),
            },
        ),
    ]
